// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kc7-jsa45CIfXw3LG2ku13jPeE7UHPw',
    appId: '1:407622917756:web:427e6022376ad8d60173f9',
    messagingSenderId: '407622917756',
    projectId: 'bullsea-io',
    authDomain: 'bullsea-io.firebaseapp.com',
    storageBucket: 'bullsea-io.appspot.com',
    measurementId: 'G-W2BF26KYWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqEde8JYfBiz0zsXkN6rGSk8KLeMDgtI',
    appId: '1:407622917756:android:eea85bd7ac80b13d0173f9',
    messagingSenderId: '407622917756',
    projectId: 'bullsea-io',
    storageBucket: 'bullsea-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbADEYhNnDYi9rubEjrjbnZXARY-aUbYw',
    appId: '1:407622917756:ios:584600dbe25c1f620173f9',
    messagingSenderId: '407622917756',
    projectId: 'bullsea-io',
    storageBucket: 'bullsea-io.appspot.com',
    iosClientId: '407622917756-ui9v7il3oc6509uuf5ctje3rfrnuh454.apps.googleusercontent.com',
    iosBundleId: 'com.example.bullsea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbADEYhNnDYi9rubEjrjbnZXARY-aUbYw',
    appId: '1:407622917756:ios:584600dbe25c1f620173f9',
    messagingSenderId: '407622917756',
    projectId: 'bullsea-io',
    storageBucket: 'bullsea-io.appspot.com',
    iosClientId: '407622917756-ui9v7il3oc6509uuf5ctje3rfrnuh454.apps.googleusercontent.com',
    iosBundleId: 'com.example.bullsea',
  );
}
